config/routes.rb
Rails.application.routes.draw do
  get 'transaction_files/new'
  get 'transaction_files/create'
  root "companies#index"

  resources :companies, only: [:index] do
    resources :sales, only: [:index]
    resources :transaction_files, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :sales
  has_many :transaction_files
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :company
  belongs_to :transaction_file
end

app/models/transaction_file.rb
class TransactionFile < ApplicationRecord
  belongs_to :company
  
  has_one_attached :file
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.includes(:sales).all
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_company

  def index
    @sales = @company.sales
  end

  private 

  def set_company
    @company = Company.includes(:sales).find(params[:company_id])
  end
end

app/controllers/transaction_files_controller.rb
class TransactionFilesController < ApplicationController
  before_action :set_company

  def new
    @transaction_file = TransactionFile.new
  end

  def create
    TransactionFile.create!(transaction_file_params.merge(company_id: @company.id))

    redirect_to company_sales_path(@company)
  end

  private 

  def set_company
    @company  = Company.find(params[:company_id])
  end

  def transaction_file_params
    params.require(:transaction_file).permit(:file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/index.html.erb
<h1>Companies</h1>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% @companies.each do |company| %>
    <tr>
      <td><%= company.name %></td>
      <td><%= link_to("Sales", company_sales_path(company) )%></td>
    </tr>
  <% end -%>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CompanySales</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sales/index.html.erb
<h1>Company name: <%= @company.name %></h1>

<%= link_to("Import new file", new_company_transaction_file_path(@company)) %>
<h3>Sales</h3>

<table>
  <tr>
    <th>Purchaser Name</th>
    <th>Item Description</th>
    <th>Item Price</th>
    <th>Purchase Count</th>
    <th>Merchant Address</th>
    <th>Merchant Name</th>
  </tr>
  <% @sales.each do |sale| %>
    <tr>
      <td><%= sale.purchaser_name %></td>
      <td><%= sale.item_description %></td>
      <td><%= sale.item_price %></td>
      <td><%= sale.purchase_count %></td>
      <td><%= sale.merchant_address %></td>
      <td><%= sale.merchant_name %></td>
    </tr>
  <% end -%>
</table>

app/views/transaction_files/new.html.erb
<h1>Import sales</h1>

<%= link_to("Sales", company_sales_path(@company)) %>


<%= form_with model: @transaction_file, url: [@company, @transaction_file] do |form| %>
  <%= form.file_field :file %>
  <%= form.submit %>
<% end -%>